### ISSUE TITLE
Fibonacci series

### ISSUE THREAD

**Issue by asarfraaz** [Fearsomemaster/PythonTraining#1]
Have you tested the Fibonacci series code ? Do they give the expected results ?

**Comment by Fearsomemaster** [comment]
Yes Sarfraaz, It is working

**Comment by Fearsomemaster** [comment]
> Have you tested the Fibonacci series code ? Do they give the expected results ?
Yes Sarfraaz, It is working
![image](https://user-images.githubusercontent.com/83412879/142139167-7a372856-2135-4cbf-8ee2-a00e33494060.png)
![image](https://user-images.githubusercontent.com/83412879/142139211-659b168c-651b-4cb9-b30d-8c4ded8b3e78.png)

**Comment by asarfraaz** [comment]
Ok. Good. Can you rework the solution using the logic we wrote in the class ?
```
a = a + b
b = a + b
```
